//! `LocalProvider`: a deterministic provider used for tests and offline runs.
//! It performs no network I/O and returns a fixed transform of the prompt.

use crate::Provider;
use crate::{CompleteRequest, CompleteResponse};
use async_trait::async_trait;

/// A provider whose output is a pure function of its input — used to drive the
/// spine deterministically in CI.
pub struct LocalProvider;

impl LocalProvider {
    pub fn new() -> Self {
        Self
    }
}

impl Default for LocalProvider {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Provider for LocalProvider {
    fn id(&self) -> &str {
        "local"
    }

    fn is_offline(&self) -> bool {
        true
    }

    async fn complete(&self, req: CompleteRequest) -> anyhow::Result<CompleteResponse> {
        Ok(CompleteResponse {
            text: format!("// generated by otto local provider\n{}\n", req.prompt),
            usage: None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn complete_is_deterministic() {
        let provider = LocalProvider::new();
        let req = CompleteRequest {
            prompt: "add a greeting".to_string(),
        };
        let a = provider.complete(req.clone()).await.unwrap();
        let b = provider.complete(req).await.unwrap();
        assert_eq!(a, b);
        assert!(a.text.contains("add a greeting"));
        assert_eq!(provider.id(), "local");
    }

    #[test]
    fn local_provider_is_the_offline_fallback() {
        assert!(LocalProvider::new().is_offline());
    }
}
