[package]
name = "light-factory-persistence"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
light-factory-auth = { path = "../auth" }
sqlx = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = "0.1"
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
